specVersion: 1.0.0
name: subql_bifrost_for_vfil
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: For Bifrost vFil project
repository: https://github.com/subquery/bifrost-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: ws://172.19.64.5:9866
  genesisHash: '0xbf5a84fa2855d9a1fba6864e5f490291f0a8eb1e74fbb9ade04acb9a04240591'
  dictionary: https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
      # VtokenMinting module handlers
        - handler: handleVtokenMintingMinted
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Minted
        - handler: handleVtokenMintingRedeemed
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Redeemed
      # SLP module handlers
        - handler: handleSlpRefund
          kind: substrate/EventHandler
          filter:
            module: slp
            method: Refund
        - handler: handleSlpTransferTo
          kind: substrate/EventHandler
          filter:
            module: slp
            method: TransferTo
      # CrossInOut module handlers
        - handler: handleCrossInOutCrossedIn
          kind: substrate/EventHandler
          filter:
            module: crossInOut
            method: CrossedIn
        - handler: handleCrossInOutCrossedOut
          kind: substrate/EventHandler
          filter:
            module: crossInOut
            method: CrossedOut