specVersion: 0.2.0
name: subql_bifrost_for_vfil
version: 1.0.0
description: For Bifrost vFil project
repository: https://github.com/subquery/bifrost-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://bifrost-parachain.api.onfinality.io/public-ws
  genesisHash: '0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed'
  dictionary: https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 2723000
    mapping:
      file: ./dist/index.js
      handlers:
      # VtokenMinting module handlers
        - handler: handleVtokenMintingMinted
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Minted
        - handler: handleVtokenMintingRedeemed
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Redeemed
      # SLP module handlers
        - handler: handleSlpRefund
          kind: substrate/EventHandler
          filter:
            module: slp
            method: Refund
        - handler: handleSlpTransferTo
          kind: substrate/EventHandler
          filter:
            module: slp
            method: TransferTo
      # CrossInOut module handlers
        - handler: handleCrossInOutCrossedIn
          kind: substrate/EventHandler
          filter:
            module: crossInOut
            method: CrossedIn
        - handler: handleCrossInOutCrossedOut
          kind: substrate/EventHandler
          filter:
            module: crossInOut
            method: CrossedOut