apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: vfil1-subql
    qcloud-app: vfil1-subql
  name: vfil1-subql
  namespace: vfil-proc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: vfil1-subql
      qcloud-app: vfil1-subql
  template:
    metadata:
      labels:
        k8s-app: vfil1-subql
        qcloud-app: vfil1-subql
    spec:
      containers:
      - args:
        - -f=/app
        - --local
        - --timestamp-field
        env:
        - name: DB_DATABASE
          value: vfil1
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          value: *
        - name: DB_HOST
          value: *
        - name: DB_PORT
          value: '30435'
        image: harbor.liebi.com/vfil/vfil-subql:63d8494-proc
        imagePullPolicy: Always
        name: vfil1-subql
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
      imagePullSecrets:
      - name: harbor
      restartPolicy: Always